# SwiftLint configuration for KimaiClock

strict: true

included:
  - App.swift
  - KimaiClock
excluded:
  - Pods
  - .build
  - Scripts
  - fastlane
  - Carthage

disabled_rules:
  - line_length
  - implicit_return
  - identifier_name
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure

opt_in_rules:
  - empty_count
  - sorted_imports
  - implicit_return
  - no_fallthrough_only
  - discouraged_object_literal
  - vertical_parameter_alignment_on_call

trailing_whitespace:
  ignores_empty_lines: false

reporter: "xcode"
