require 'dotenv'

Dotenv.load unless ENV['APPLE_ID']

default_platform(:mac)

platform :mac do
  desc "Build, notarize, create DMG, and release"
  lane :release do

    increment_build_number(
      xcodeproj: "KimaiClock.xcodeproj"
    )

    build_mac_app(
      configuration: 'Release',
      export_method: "developer-id",
      xcargs: '-allowProvisioningUpdates'
    )

    notarize(
      package: "KimaiClock.app",
      username: ENV["APPLE_ID"],
      asc_provider: ENV["APPLE_PROVIDER"],
      use_notarytool: true
    )
  end
end
