name: Linting

on:
  push:

jobs:
  lint:
    name: Run SwiftLint
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SwiftLint
        run: |
          brew install swiftlint || echo "SwiftLint already installed"

      - name: Run SwiftLint
        run: swiftlint --strict
