name: Build, Sign, Notarize, and Release macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          show-progress: false

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install Fastlane
        run: gem install fastlane

      - name: Install create-dmg
        run: |
          brew install create-dmg graphicsmagick imagemagick

      - name: Run Fastlane
        run: fastlane release
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
          BUNDLE_ID: ${{ secrets.BUNDLE_ID }}

      - name: Compute SHA256
        id: hash
        run: |
          shasum -a 256 build/KimaiClock/KimaiClock.dmg > build/KimaiClock/KimaiClock.dmg.sha256

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: build/KimaiClock/KimaiClock.dmg,build/KimaiClock/KimaiClock.dmg.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
